# Generated by Django 2.0.2 on 2018-02-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('country_code', models.CharField(max_length=5)),
            ],
        ),
    ]
